require "user.options"
require "user.keymaps"
require "user.utils"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.telescope"
-- require "user.project"
require "user.gitsigns"
require "user.treesitter"
require "user.autopairs"
require "user.nvim-tree"
require "user.bufferline"
require "user.lualine"
-- require "user.toggleterm"
require "user.impatient"
require "user.indentline"
require "user.alpha"
require "user.whichkey"
require "user.autocommands"
require "user.undotree"
require "user.leap"
require "user.neoscroll"
require "user.noice"
require "user.comment"
require "user.surround"

